# Generated by Django 2.0.3 on 2018-08-20 00:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charity', '0010_auto_20180730_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('charity_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.CharityProfile')),
            ],
        ),
    ]
