# Generated by Django 2.0.3 on 2018-08-20 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='charity_profile',
            new_name='charityprofile',
        ),
    ]
