# Generated by Django 2.0.3 on 2018-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charityprofile',
            old_name='charity_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='charityprofile',
            name='charity_email',
        ),
        migrations.AddField(
            model_name='charityprofile',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='charityprofile',
            name='img_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='charityprofile',
            name='money_raised',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
