# Generated by Django 2.0.3 on 2018-07-01 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0002_auto_20180624_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='is_displayed',
            field=models.BooleanField(default=True),
        ),
    ]
