# Generated by Django 2.0.3 on 2018-07-01 23:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_charityprofile_is_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('charityprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.CharityProfile')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charity.Campaign')),
            ],
        ),
    ]
