# Generated by Django 2.0.3 on 2018-07-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0005_auto_20180701_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(default='Tester Campaign Name', max_length=200),
            preserve_default=False,
        ),
    ]
