# Generated by Django 2.0.3 on 2018-07-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
