# Generated by Django 2.0.3 on 2018-07-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_charityprofile_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='long_bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
