# Generated by Django 2.0.3 on 2018-10-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0010_auto_20180730_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charityprofile',
            name='money_raised',
        ),
        migrations.AlterField(
            model_name='charityprofile',
            name='charity_url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
