# Generated by Django 2.0.10 on 2019-01-28 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0011_auto_20181013_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='charityprofile',
            name='is_password_reset',
            field=models.BooleanField(default=False),
        ),
    ]
